#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "__NAME__"
email = "__EMAIL__"

[ui]
default-command = "log"
diff.format = "git"
pager = "delta"

[git]
auto-local-bookmark = false
