"""Theme generation — reads themes.toml, produces all config outputs."""

import tomllib
from pathlib import Path

THEMES_TOML = Path(__file__).parent / "themes.toml"


def load_themes() -> dict:
    return tomllib.loads(THEMES_TOML.read_text())


# ── Color utilities ──────────────────────────────────────────

def hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def rgb_to_hex(r: int, g: int, b: int) -> str:
    return f"#{r:02x}{g:02x}{b:02x}"


def blend(c1: str, c2: str, t: float) -> str:
    """Blend c1 toward c2 by factor t (0.0 = pure c1, 1.0 = pure c2)."""
    r1, g1, b1 = hex_to_rgb(c1)
    r2, g2, b2 = hex_to_rgb(c2)
    return rgb_to_hex(
        round(r1 + (r2 - r1) * t),
        round(g1 + (g2 - g1) * t),
        round(b1 + (b2 - b1) * t),
    )


def ansi_rgb(h: str) -> str:
    """Convert #rrggbb to R;G;B for shell ANSI escape codes."""
    r, g, b = hex_to_rgb(h)
    return f"{r};{g};{b}"


# ── File generators (return complete file contents) ──────────

def ghostty_theme(theme: dict) -> str:
    b = theme["base"]
    t = theme["terminal"]
    lines = [
        f"# {theme['name']} — terminal theme",
        f"# {theme['tagline']}",
        "",
        f"background = {b['bg']}",
        f"foreground = {b['fg']}",
        f"cursor-color = {t['cursor']}",
        f"cursor-text = {t['cursor_text']}",
        f"selection-background = {t['sel_bg']}",
        f"selection-foreground = {t['sel_fg']}",
        "",
        "# ANSI Normal",
    ]
    for i, c in enumerate(t["ansi"]):
        lines.append(f"palette = {i}={c}")
    lines += ["", "# ANSI Bright"]
    for i, c in enumerate(t["ansi_bright"]):
        lines.append(f"palette = {i + 8}={c}")
    return "\n".join(lines) + "\n"


def nvim_theme_colors(theme: dict) -> str:
    """Generate a lua file returning catppuccin mocha color overrides."""
    b = theme["base"]
    a = theme["accents"]
    colors = {
        "base": b["bg"],
        "mantle": b["dim"],
        "crust": blend(b["dim"], "#000000", 0.3),
        "surface0": b["accent"],
        "surface1": b["sel"],
        "surface2": blend(b["sel"], b["fg"], 0.15),
        "overlay0": blend(b["sel"], b["dim_fg"], 0.5),
        "overlay1": b["dim_fg"],
        "overlay2": blend(b["dim_fg"], b["fg"], 0.3),
        "text": b["fg"],
        "subtext0": blend(b["dim_fg"], b["fg"], 0.4),
        "subtext1": blend(b["dim_fg"], b["fg"], 0.7),
        "lavender": a["secondary"],
        "blue": a["secondary"],
        "sapphire": blend(a["secondary"], b["bg"], 0.2),
        "sky": blend(a["secondary"], b["bright"], 0.2),
        "teal": a["primary"],
        "green": a["success"],
        "yellow": a["yellow"],
        "peach": a["warn"],
        "maroon": a["error"],
        "red": a["error"],
        "mauve": a["purple"],
        "pink": a["pink"],
        "flamingo": a["pink"],
        "rosewater": b["bright"],
    }
    lines = ["-- Generated by setup.py from themes.toml — do not edit", "return {"]
    for k, v in colors.items():
        lines.append(f'  {k} = "{v}",')
    lines.append("}")
    return "\n".join(lines) + "\n"


def nvim_dashboard_colors(theme: dict) -> str:
    """Generate a lua file returning dashboard header + highlight color."""
    a = theme["accents"]
    label = theme["name"].lower()
    return "\n".join([
        "-- Generated by setup.py from themes.toml — do not edit",
        "return {",
        f'  header_color = "{a["primary"]}",',
        f'  header_text = "░▒▓  {label}  ▓▒░",',
        "}",
    ]) + "\n"


def lazygit_config(theme: dict) -> str:
    b = theme["base"]
    a = theme["accents"]
    return f"""\
# Generated by setup.py from themes.toml — do not edit
gui:
  theme:
    activeBorderColor:
      - "{a['primary']}"
      - bold
    inactiveBorderColor:
      - "{b['dim_fg']}"
    searchingActiveBorderColor:
      - "{a['secondary']}"
      - bold
    optionsTextColor:
      - "{a['secondary']}"
    selectedLineBgColor:
      - "{b['accent']}"
    cherryPickedCommitFgColor:
      - "{a['yellow']}"
    unstagedChangesColor:
      - "{a['error']}"
    defaultFgColor:
      - "{b['fg']}"
"""


def btop_theme(theme: dict) -> str:
    """Generate a btop color theme file."""
    b = theme["base"]
    a = theme["accents"]

    def line(key: str, val: str) -> str:
        return f'theme[{key}]="{val}"'

    lines = [
        f"# {theme['name']} — btop theme",
        f"# Generated by setup.py from themes.toml — do not edit",
        "",
        line("main_bg", b["bg"]),
        line("main_fg", b["fg"]),
        line("title", b["bright"]),
        line("hi_fg", a["primary"]),
        line("selected_bg", b["accent"]),
        line("selected_fg", b["bright"]),
        line("inactive_fg", b["dim_fg"]),
        line("graph_text", b["dim_fg"]),
        line("meter_bg", b["sel"]),
        line("proc_misc", a["yellow"]),
        line("cpu_box", a["primary"]),
        line("mem_box", a["success"]),
        line("net_box", a["secondary"]),
        line("proc_box", a["purple"]),
        line("div_line", b["sel"]),
        line("temp_start", a["success"]),
        line("temp_mid", a["yellow"]),
        line("temp_end", a["error"]),
        line("cpu_start", a["primary"]),
        line("cpu_mid", blend(a["primary"], a["warn"], 0.5)),
        line("cpu_end", a["warn"]),
        line("free_start", a["success"]),
        line("free_mid", blend(a["success"], a["yellow"], 0.5)),
        line("free_end", a["yellow"]),
        line("cached_start", a["secondary"]),
        line("cached_mid", blend(a["secondary"], a["purple"], 0.5)),
        line("cached_end", a["purple"]),
        line("available_start", a["pink"]),
        line("available_mid", blend(a["pink"], a["warn"], 0.5)),
        line("available_end", a["warn"]),
        line("used_start", a["warn"]),
        line("used_mid", blend(a["warn"], a["error"], 0.5)),
        line("used_end", a["error"]),
        line("download_start", a["primary"]),
        line("download_mid", blend(a["primary"], a["secondary"], 0.5)),
        line("download_end", a["secondary"]),
        line("upload_start", a["warn"]),
        line("upload_mid", blend(a["warn"], a["pink"], 0.5)),
        line("upload_end", a["pink"]),
        line("process_start", a["secondary"]),
        line("process_mid", blend(a["secondary"], a["primary"], 0.5)),
        line("process_end", a["primary"]),
    ]
    return "\n".join(lines) + "\n"


# ── Placeholder generators (for template substitution) ───────

def theme_placeholders(theme: dict) -> dict[str, str]:
    """Return {__PLACEHOLDER__: value} dict for all theme template vars."""
    b = theme["base"]
    a = theme["accents"]
    t = theme["terminal"]

    return {
        "__THEME_NAME__": theme["name"],

        # fzf (shell/zshrc)
        "__THEME_FZF_COLORS__": _fzf_colors(b, a),

        # motd (shell/zshrc)
        "__THEME_MOTD__": _motd_block(theme),

        # delta (git/gitconfig)
        "__THEME_DELTA__": _delta_block(b, a),

        # starship
        "__THEME_DIR_COLOR__": a["secondary"],
        "__THEME_SUCCESS_COLOR__": a["primary"],
        "__THEME_ERROR_COLOR__": a["error"],

        # claude statusline
        "__THEME_PALETTE__": _statusline_palette(b, a),

        # lazyjj (jj/config.toml)
        "__THEME_HIGHLIGHT_COLOR__": a["primary"],
    }


def _fzf_colors(b: dict, a: dict) -> str:
    return "\n".join([
        f"  --color=bg+:{b['sel']},bg:{b['bg']},spinner:{a['primary']},hl:{a['warn']}",
        f"  --color=fg:{b['fg']},header:{a['secondary']},info:{a['primary']},pointer:{a['warn']}",
        f"  --color=marker:{a['success']},fg+:{b['bright']},prompt:{a['primary']},hl+:{a['warn']}",
        f"  --color=border:{b['sel']}",
    ])


def _motd_block(theme: dict) -> str:
    icon = theme.get("motd_icon", "")
    label = theme["name"].lower()
    p_rgb = ansi_rgb(theme["accents"]["primary"])
    d_rgb = ansi_rgb(theme["base"]["dim_fg"])
    return "\n".join([
        'if [[ -o interactive ]] && [[ -z "$DOTFILES_MOTD_SHOWN" ]]; then',
        '    export DOTFILES_MOTD_SHOWN=1',
        '    echo ""',
        f'    echo -e "\\033[38;2;{p_rgb}m  {icon} {label}\\033[0m"',
        f'    echo -e "\\033[38;2;{d_rgb}m  ── dev environment v1.0\\033[0m"',
        '    echo ""',
        'fi',
    ])


def _delta_block(b: dict, a: dict) -> str:
    minus_bg = blend(b["bg"], a["error"], 0.12)
    minus_emph = blend(b["bg"], a["error"], 0.22)
    plus_bg = blend(b["bg"], a["success"], 0.12)
    plus_emph = blend(b["bg"], a["success"], 0.22)
    hunk_bg = blend(b["bg"], a["secondary"], 0.12)
    hunk_border = blend(a["secondary"], b["fg"], 0.3)
    ln_zero = blend(b["sel"], b["dim_fg"], 0.5)
    blame = " ".join([
        b["bg"],
        blend(b["bg"], a["secondary"], 0.08),
        blend(b["bg"], a["secondary"], 0.15),
        blend(b["bg"], a["purple"], 0.10),
        blend(b["bg"], a["primary"], 0.10),
    ])
    lines = [
        "navigate = true",
        "\tdark = true",
        "\tside-by-side = true",
        "\tline-numbers = true",
        "\tsyntax-theme = base16",
        f'\tminus-style = "syntax {minus_bg}"',
        f'\tminus-emph-style = "syntax {minus_emph}"',
        f'\tplus-style = "syntax {plus_bg}"',
        f'\tplus-emph-style = "syntax {plus_emph}"',
        f'\tline-numbers-minus-style = "{a["purple"]}"',
        f'\tline-numbers-plus-style = "{a["primary"]}"',
        f'\tline-numbers-zero-style = "{ln_zero}"',
        f'\tfile-style = "bold {a["pink"]}"',
        f'\tfile-decoration-style = "{a["pink"]} ul"',
        f'\thunk-header-style = "syntax {hunk_bg}"',
        f'\thunk-header-decoration-style = "{hunk_border} box"',
        "\tzero-style = syntax",
        f'\tblame-palette = "{blame}"',
    ]
    return "\n".join(lines)


def _statusline_palette(b: dict, a: dict) -> str:
    return "\n".join([
        f"DIM='\\033[38;2;{ansi_rgb(b['dim_fg'])}m'",
        f"SEP='\\033[38;2;{ansi_rgb(b['sel'])}m'",
        f"BLUE='\\033[38;2;{ansi_rgb(a['secondary'])}m'",
        f"TEAL='\\033[38;2;{ansi_rgb(a['primary'])}m'",
        f"ORANGE='\\033[38;2;{ansi_rgb(a['warn'])}m'",
        f"GOLD='\\033[38;2;{ansi_rgb(a['yellow'])}m'",
        f"RED='\\033[38;2;{ansi_rgb(a['error'])}m'",
    ])
