-- Theme colors are generated by setup.py from themes.toml
local colors_file = os.getenv("HOME") .. "/.config/dotfiles/theme_colors.lua"
local ok, colors = pcall(dofile, colors_file)
if not ok then
  colors = nil
end

return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      flavour = "mocha",
      color_overrides = colors and {
        mocha = colors,
      } or {},
      integrations = {
        cmp = true,
        gitsigns = true,
        mason = true,
        mini = true,
        native_lsp = { enabled = true },
        notify = true,
        telescope = { enabled = true },
        treesitter = true,
        which_key = true,
      },
    },
  },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
}
