-- Dashboard config — header is generated by setup.py from themes.toml
local dash_file = os.getenv("HOME") .. "/.config/dotfiles/dashboard_colors.lua"
local ok, dash = pcall(dofile, dash_file)
if not ok then
  dash = { header_color = "#40bfb0", header_text = "░▒▓  dotfiles  ▓▒░" }
end

return {
  {
    "folke/snacks.nvim",
    opts = {
      dashboard = {
        preset = {
          header = table.concat({
            "",
            "   " .. dash.header_text,
            "",
            "   ── nvim ──",
            "",
          }, "\n"),
        },
      },
    },
    init = function()
      local ok2, d = pcall(dofile, os.getenv("HOME") .. "/.config/dotfiles/dashboard_colors.lua")
      if not ok2 then d = {} end
      vim.api.nvim_set_hl(0, "SnacksDashboardHeader", { fg = d.header_color or "#40bfb0" })
    end,
  },
}
